### ISSUE TITLE
Account taken over by hacker

### ISSUE THREAD

**Issue by 32bpwr3** [Gazerbeamco/humansupport#10]
https://www.reddit.com/r/facebook/comments/o8ye8p/i_am_offering_honest_free_user_support_to_anybody/h39ifm6?utm_source=share&utm_medium=web2x&context=3

**Comment by Brokenheart00** [comment]
Hi,I new to this so can anybody told me how to hack facebook. My fb was taken by someone and i really want it back😢

**Comment by 32bpwr3** [comment]
@Brokenheart00 Hey sorry I didn't see your message until now. Are you adding to this issue or are you reporting your own Facbook account problem story? If you have a story of your own to share, please submit it here: https://airtable.com/shrpF3t3R1Ul3YBE2. I changed how I am collecting the feedback. If you need to reach me, send email to humansupport@gazerbeam.com. Thanks!
